services:
  fks_ninja:
    build:
      context: .
      dockerfile: Dockerfile
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "dotnet --info >/dev/null 2>&1 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  fks_net:
    name: fks_net